-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-12 20:41:06 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dim_date (
    date_value   DATE NOT NULL,
    id           INTEGER NOT NULL
);

ALTER TABLE dim_date ADD CONSTRAINT publish_date_pk PRIMARY KEY ( id );

CREATE TABLE dim_tags (
    tag_id      INTEGER NOT NULL,
    tag_value   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE dim_tags ADD CONSTRAINT tags_pk PRIMARY KEY ( tag_id );

CREATE TABLE fact_tag_on_post (
    publish_date      DATE,
    fact_id           INTEGER NOT NULL,
    tag_id            INTEGER,
    dim_date_id       INTEGER NOT NULL,
    dim_tags_tag_id   INTEGER NOT NULL,
    view_count        INTEGER,
    score             INTEGER
);

ALTER TABLE fact_tag_on_post ADD CONSTRAINT fact_tag_on_post_pk PRIMARY KEY ( fact_id );

ALTER TABLE fact_tag_on_post
    ADD CONSTRAINT fact_tag_on_post_dim_date_fk FOREIGN KEY ( dim_date_id )
        REFERENCES dim_date ( id );

ALTER TABLE fact_tag_on_post
    ADD CONSTRAINT fact_tag_on_post_dim_tags_fk FOREIGN KEY ( dim_tags_tag_id )
        REFERENCES dim_tags ( tag_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
